### ISSUE TITLE
Coveralls jobs "missing" coverage data

### ISSUE THREAD

**Issue by AlCalzone** [nickmerwin/node-coveralls#185]
I'm not sure if this is an issue with coveralls or this library, so I'm posting this here.
For my recent builds, coveralls shows no coverage data under jobs, but correctly shows changes in the source files, see:
![unbenannt](https://user-images.githubusercontent.com/17641229/37042996-e1bad0f0-215f-11e8-947c-88d8ab71b356.PNG)
This was for a test commit (PR) where I removed almost all test cases to see if things change:
https://github.com/AlCalzone/node-tradfri-client/pull/34

The same thing currently happens on the master branch. My `.travis.yml` looks like this:
```yaml
language: node_js
node_js:
  - '6'
  - '8'
os:
  - linux
script: 
  - npm run coverage
after_success: 
  - npm run coveralls
notifications:
  email: false
```
with the following scripts defined in `package.json`:
```js
// ... more ...
"scripts": {
    // ... more ...
    "coverage": "node_modules/.bin/nyc npm test",
    "coveralls": "node_modules/.bin/nyc report --reporter=text-lcov | coveralls -v",
}
```
